config/routes.rb
GreenCape::Application.routes.draw do
  get "admin/index"
  get "admin/edit_papers"
  get "home/index"
  get "home/about"
  get "home/contact"
  get "members/user_display"
  get "papers/user_display"
  

  resources :papers
  resources :members
  resources :admin

  devise_for :users
  

  root :to => "Home#index"

end

app/models/member.rb
class Member < ActiveRecord::Base
  validates :first_name, :last_name, :position, :description, :presence => true
  validates_format_of :first_name, :last_name, :with => /^\D+$/,
  :message => "can contain only letters"
end

app/models/paper.rb
class Paper < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  before_filter :authenticate_user!
  layout "admin"

  def index
    @user_loggedin = current_user.email
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_user!, :except => :user_display
  layout 'admin'
  
  # GET /members
  # GET /members.xml
  def user_display
    @members = Member.all
    render :action => "user_display", :layout => "application"
  end
  
  # GET /members
  # GET /members.xml
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/new
  # GET /members/new.xml
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.xml
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to(@member, :notice => 'Member was successfully created.') }
        format.xml  { render :xml => @member, :status => :created, :location => @member }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_filter :authenticate_user!, :except => :user_display
  layout 'admin'
  
  # GET /papers
  # GET /papers.xml
  def user_display
    @members = Paper.all
    render :action => "user_display", :layout => "application"
  end
  
  # GET /papers
  # GET /papers.xml
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.xml
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.xml
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.xml
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to(@paper, :notice => 'Paper was successfully created.') }
        format.xml  { render :xml => @paper, :status => :created, :location => @paper }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.xml
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to(@paper, :notice => 'Paper was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.xml
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to(papers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/admin/edit_papers.html.erb
<br\>
<p>Edit Papers</p>

app/views/home/about.html.erb
<div class="about">
    <h2 id="about_us">About Us, powering the renewable evolution</h2>
     <p>The GreenCape Initiative embodies the strategic intent of the Provincial
     Government of the Western Cape to ensure that the Western Cape captures
     a significant share of the jobs created in the renewable and green
     economy, and is at the forefront of renewable energy and green
     technology.</p>

</div>

app/views/home/contact.html.erb
<div class="about">
  <h2 id="about_us">About Us, powering the renewable evolution</h2>
  <p></p>
</div>
<div id="contact_us">
    <h2 id="contact">Contact</h2>
    <p class="address">9th Floor
      Waldorf Building<br/>
      80 St George's Mall<br/>
      Cape Town<br/>
      8000
    </p>

    <p class="address">
      <span>E:</span>info@green-cape.co.za<br/>
      <span>T:</span>+27 21 483 3859<br/>
      <span>F:</span>+27 86 583 9213
    </p>
    <div id="email_us">
      <a href="mailto:info@green-cape.co.za">Email us</a>

    </div>
  </div>

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">

      <div class="about">
        <h2 id="about_us">About Us, powering the renewable evolution</h2>
        <p></p>
      </div>
      <div class="section">
        <img src="images/team_img.jpg"  alt="team" >
        <h2 id="team">Team</h2>
        <p>The GreenCape team is committed to ensuring the green economy flourishes in the Western Cape</p>
        <p> <span>Francois du Plessis</span><br/>

            CEO: GreenCape Initiative
        </p>
        <p>
          <span>Nigel Gwynne-Evans</span><br/>
          Director: Manufacturing Industry Development, Economic Development &amp; Tourism
        </p>
        <p>
          <span>Dipolelo J Elford</span><br/>

          Chief Director Environmental and Land Planning, Department of Environmental Affairs and Development Planning
        </p>
          <p>
          <span>Sarah Ward</span><br/>
          Head: Energy &amp; Climate Change Branch, Environmental Resource Management Department
          </p>
          <p>
          <span>Fernel Abrahams</span><br/>

          Manager: Renewable Energy Technologies, Department of Economic Development &amp; Tourism
        </p>
      </div>
      <div class="section">
        <img src="images/papers_img.jpg" alt="papers" >
        <h2 id="papers">Papers</h2>
        <p class="intro">Here are a select few papers which are pertinent to the GreenCape initiative:</p>

        <h4>Legislation</h4>
        <ul>
          <li><a href="assets/legislation/electricity_act.pdf"> Electricity Act</a></li>
          <li><a href="assets/legislation/Electricity-Regulation-Act-4-06.pdf"> Electricity Regulation Act 4-06</a></li>
          <li><a href="assets/legislation/National-Energy-Act-2008.pdf"> National Energy Act 2008</a></li>

          <li><a href="assets/conference_proceedings/National-Environmental-Management-Act-107-98.pdf"> National Environmental Management Act</a></li>
        </ul>
        <h4>Policy</h4>
        <ul>
          <li><a href="assets/policy/WC-White-Paper-Sustainable-Energy-Gazette.pdf">White Paper on Sustainable Energy</a></li>
          <li><a href="assets/policy/SA-Renewable-Energy-White-Paper-2004.pdf">SA Renewable Energy White Paper</a></li>

        </ul>
        <!--h4>Action Plans</h4-->
        <h4>Position Papers</h4>
          <ul>
            <li><a href="assets/position/greentech-12-04-2010.pdf">Green Tech</a></li>
          </ul>
        <!-- <h4>Conference proceedings</h4>
          <ul>
            <li></li>
          </ul> -->
      </div>

      <div id="contact_us">
        <h2 id="contact">Contact</h2>
        <p class="address">9th Floor
          Waldorf Building<br/>
          80 St George's Mall<br/>
          Cape Town<br/>
          8000
        </p>

        <p class="address">
          <span>E:</span>info@green-cape.co.za<br/>
          <span>T:</span>+27 21 483 3859<br/>
          <span>F:</span>+27 86 583 9213
        </p>
        <div id="email_us">
          <a href="mailto:info@green-cape.co.za">Email us</a>

        </div>
      </div>
      

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenCape - Admin</title>
  <%= stylesheet_link_tag "scaffold", "admin"%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Green Cape - Admin</title>
</head>

<h1 id='admin'>Administrator Page - Logged in as  : <%= @user_loggedin %><h1/>
	<p><%=link_to 'Edit Team', members_path %>  |  <%=link_to 'Edit Papers', admin_edit_papers_path %></p>
<hr />
<%= yield %>
<hr />
<p id='footer'><%=link_to 'Log out', destroy_user_session_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenCape</title>
  <%= stylesheet_link_tag "user",  "http://yui.yahooapis.com/2.8.2r1/build/reset/reset-min.css"%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Green Cape</title>
  <meta name="author" content="Simon Rentzke">
  <meta name="description" content="The GreenCape Initiative embodies the strategic intent of the Provincial
  Government of the Western Cape to:Ensure that the Western Cape is at the forefront of renewable
  energy and green technology; Ensure that the Western Cape captures a significant share of the
  jobs created in the renewable and green economy; Promote the transition of the Western Cape economy to greater
  resource efficiency and a low-carbon future">

  <!--[if lte IE 6]><link href="stylesheets/ie6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<html lang="en">
<body>
  <div id="main">
    <div id="content">
      <div id="header">
        <h1 id="green_cape_logo"><a href="http://www.green-cape.co.za">Green Cape</a></h1>
        <ul id="nav">
          <li><%=link_to 'about', home_about_path %></li>
          <li><%=link_to 'papers', papers_user_display_path %></li>
          <li><%=link_to 'team', members_user_display_path %></li>
          <li class="last"><%=link_to 'contact', home_contact_path %></li>
        </ul>
      </div>

		<%= yield %>
		
		<div id="footer">
	        <img src="/images/footer_logos.jpg" id="sponsor_logos" alt="sponsor logos" >
	        <div id="copyright"><img src="/images/ftr_gclogo.gif" width="239" height="57" alt="Green Cape"></div>
	      </div>
	    </div>
	  </div>
	  <script type="text/javascript">
	    var _gaq = _gaq || [];
	    _gaq.push(['_setAccount', 'UA-19523803-1']);
	    _gaq.push(['_trackPageview']);
	    (function() {
	      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	    })();
	  </script>

	</body>
	</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>
      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing Team members</h1>

<div class="section">
  <h2 id="team">Team</h2>
  <p>The GreenCape team is committed to ensuring the green economy flourishes in the Western Cape</p>

<% @members.each do |member| %>

<td class="list_description">
    <dl>
      <dt><%= member.first_name%> <%= member.last_name%></dt>
	  <dt><%= member.position%>: <%= member.description%></dt>
    </dl>
</td>

<tr>
  <td><%= link_to 'Show', member %></td>
  <td><%= link_to 'Edit', edit_member_path(member) %></td>
  <td><%= link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>


<br />

<%= link_to 'New Member', new_member_path %>

</div>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First Name:</b>
  <%= @member.first_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @member.last_name %>
</p>

<p>
  <b>Position:</b>
  <%= @member.position %>
</p>

<p>
  <b>Description:</b>
  <%= @member.description %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/members/user_display.html.erb
<div class="about">
  <h2 id="about_us">About Us, powering the renewable evolution</h2>
  <p></p>
</div>
<div class="section">
  <img src="/images/team_img.jpg"  alt="team" >
  <h2 id="team">Team</h2>
  <p>The GreenCape team is committed to ensuring the green economy flourishes in the Western Cape</p>

<% @members.each do |member| %>

<p>
  <span><%= member.first_name%> <%= member.last_name%></span><br/>
  <%= member.position%>: <%= member.description%>
</p>


<% end %>
</table>
</div>

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :extention %><br />
    <%= f.text_field :extention %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<h1>Listing papers</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Type</th>
    <th>Extention</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= paper.title %></td>
    <td><%= paper.type %></td>
    <td><%= paper.extention %></td>
    <td><%= link_to 'Show', paper %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Destroy', paper, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @paper.title %>
</p>

<p>
  <b>Type:</b>
  <%= @paper.type %>
</p>

<p>
  <b>Extention:</b>
  <%= @paper.extention %>
</p>


<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>

app/views/papers/user_display.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">

<div class="about">
  <h2 id="about_us">About Us, powering the renewable evolution</h2>
  <p></p>
</div>
<div class="section">
  <img src="/images/papers_img.jpg" alt="papers" >
  <h2 id="papers">Papers</h2>
  <p class="intro">Here are a select few papers which are pertinent to the GreenCape initiative:</p>

  <h4>Legislation</h4>
  <ul>
    <li><a href="assets/legislation/electricity_act.pdf"> Electricity Act</a></li>
    <li><a href="assets/legislation/Electricity-Regulation-Act-4-06.pdf"> Electricity Regulation Act 4-06</a></li>
    <li><a href="assets/legislation/National-Energy-Act-2008.pdf"> National Energy Act 2008</a></li>

    <li><a href="assets/conference_proceedings/National-Environmental-Management-Act-107-98.pdf"> National Environmental Management Act</a></li>
  </ul>
  <h4>Policy</h4>
  <ul>
    <li><a href="assets/policy/WC-White-Paper-Sustainable-Energy-Gazette.pdf">White Paper on Sustainable Energy</a></li>
    <li><a href="assets/policy/SA-Renewable-Energy-White-Paper-2004.pdf">SA Renewable Energy White Paper</a></li>

  </ul>
  <!--h4>Action Plans</h4-->
  <h4>Position Papers</h4>
    <ul>
      <li><a href="assets/position/greentech-12-04-2010.pdf">Green Tech</a></li>
    </ul>
  <!-- <h4>Conference proceedings</h4>
    <ul>
      <li></li>
    </ul> -->
</div>